<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="System.IO.Pipelines" Version="10.0.10" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="SignalApp.Protocol.Tests" />
  </ItemGroup>
  
</Project>
