<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>client.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="client.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignalApp.Core\SignalApp.Core.csproj" />
    <ProjectReference Include="..\SignalApp.Utils.Wpf\SignalApp.Utils.Wpf.csproj" />
  </ItemGroup>

</Project>
